<a href="https://colab.research.google.com/github/AsiaZendarska/data-science-bootcamp/blob/main/Kurs_udemy_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KURS DATA SCIENCE


# WPROWADZENIE NUMPY

Jest to podstawowa biblioteka do obliczeń numerycznych w jezyku Python.

Strona biblioteki: https://numpy.org/

Dokumentacja: https://numpy.org/doc/

## Podstawy

In [2]:
# inmportujemy i sprawdzamy wersję biblioteki
import numpy as np
np.__version__

'1.25.2'

In [ ]:
# podglądamy co ta biblioteka ma w sobie
print(dir(np))

In [ ]:
# wyświetlamy pomoc do tworzenia tablicy, można się tym posługiwać jeśli się czegoś zapomniało
help(np.array)

## 1D Array (tablica jednowymiarowa)

In [ ]:
# w tablicy każdy element musi być tego samego typu, wymiary nazywane są osiami czyli axes
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
# Obiekt klasy nd.array
type(x)

numpy.ndarray

In [ ]:
# wymiar naszej tablicy
x.ndim

1

In [ ]:
# kształ naszej tablicy
x.shape

(2,)

In [ ]:
# podaje liczbę elementów w naszej tablicy
x.size

2

In [ ]:
# okresla typ naszych danyc
x.dtype

dtype('int64')

In [ ]:
# jednowymiarowa tablica o innych wymiarach, lista, wartosci typu float
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

## 2D Array (tablica dwuwymiarowa)

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

## 3D Array (tablica trzywymiarowa)

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape # dwie tablice, dwa wiersze o trzy kolumny

(3, 2, 3)

## Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1, 2, 3], dtype='float') # przekazujemy jaki typ danych ma być
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

In [ ]:
A = np.array([1, 2, 3], dtype='complex') # przekazujemy jaki typ danych złożonych complex
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1., 2., 3.], dtype='int') # przekazujemy jaki typ danych ma być
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8) # tablica która ma opisywać zdjęcia, typ danych int8 nie zajmuje tyle miejsca
A.dtype

dtype('uint8')

## Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11) # otrzymujemy 10 elementów, równo rozłożonych

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(2,11)

array([ 2.        ,  2.18367347,  2.36734694,  2.55102041,  2.73469388,
        2.91836735,  3.10204082,  3.28571429,  3.46938776,  3.65306122,
        3.83673469,  4.02040816,  4.20408163,  4.3877551 ,  4.57142857,
        4.75510204,  4.93877551,  5.12244898,  5.30612245,  5.48979592,
        5.67346939,  5.85714286,  6.04081633,  6.2244898 ,  6.40816327,
        6.59183673,  6.7755102 ,  6.95918367,  7.14285714,  7.32653061,
        7.51020408,  7.69387755,  7.87755102,  8.06122449,  8.24489796,
        8.42857143,  8.6122449 ,  8.79591837,  8.97959184,  9.16326531,
        9.34693878,  9.53061224,  9.71428571,  9.89795918, 10.08163265,
       10.26530612, 10.44897959, 10.63265306, 10.81632653, 11.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5)) # tablice zmiania na tablice o rozmiarze 3 na 5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(3, -1) # chemy miec 3 wiersze a python przez podanie -1 sam dobierze jak ma być podzielona

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(-1, 3) # ty chcemy miec 3 kolumny

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Podstawowe operacje na tablicach

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
A + B # żeby dodawać table należy pamiętać aby były tych samych wymiarów, i dodajemy element po elemencie

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
(2 * A) + B

array([ 9,  1, 11,  6])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [ ]:
# monożenie macierzowe
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])

In [ ]:
print(X, '\n') # robi nam przerwe  '\n'
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X,Y) # tu nam zwraca mnożenie mcierzowe, mnoży wiersz razy kolumne

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

## Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0) # ziarno losowania, chemy mieć tem sam wynik

In [ ]:
np.random.randn() # losowa liczba z rozkładu normalnego

1.764052345967664

In [ ]:
np.random.randn(10) # 10 losowych liczb z rozkładu normalnego standardowego o średniej 0 i dochyleniu standardowym 1

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand() # wartość losowa z przedziału 0:1

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10) # zwraca liczę całkowitą, losowo

3

In [ ]:
np.random.randint(low=10, high=101)

56

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
np.random.choice([4,2,1,4]) # losowo wybierze element z naszego obiektu iterowanego który przekażemy

4

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([1, 0, 5, 2, 9, 7, 4, 6, 8, 3])

## Podstawowe funkcje

In [ ]:
np.exp(1) # wykorzystywana w sieciach neuronowych czy iczeniu maszynowym

2.718281828459045

In [ ]:
np.sqrt(9) # pierwiastek

3.0

In [ ]:
np.all([2,3,1])

True

In [ ]:
np.any([1,2,1]) # sprawdza czy jaka kolwiek wartość jest prawdą

True

In [ ]:
bool(1)

True

In [ ]:
A = np.random.rand(5)
A

array([0.78821321, 0.83557863, 0.89850473, 0.39191367, 0.26795825])

In [ ]:
np.argmax(A) # zwraca nam index o najwyższej wartości

2

In [ ]:
A[np.argmax(A)] # wycina nam najwyższą wartośc

0.8985047310866423

In [ ]:
np.argmin(A) # zwraca nam index o najniższej wartości

4

In [ ]:
A[np.argmin(A)] # wycina nam najniższą wartośc

0.2679582479285999

In [ ]:
np.argsort(A) # sortuje podając indexy

array([4, 3, 0, 1, 2])

In [ ]:
np.max(A)

0.8985047310866423

In [ ]:
np.min(A)

0.2679582479285999

In [ ]:
np.mean(A) # średnia

0.6364336966226215

In [ ]:
np.median(A) # mediana

0.7882132052329485

In [ ]:
np.std(A) # odchylenie standarodwe

0.25571122322399115

## Indeksowanie, Wycinanie

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[idx start, idx stop], A[:,idx stop], A[start idx, :]

## Iteracja po tablicach

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0,2]] # wycina nam dwa indexy

array([0, 2])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1] # wycinami pierwszy wiersz

array([5, 6, 7, 8, 9])

In [ ]:
A[:,0] #wycina nam kolumny

array([ 0,  5, 10, 15])

In [ ]:
A[1, 3] #wycinamy konkretną liczbę

8

In [ ]:
A[1:3, 1:4] # wycina konkretny fragmen z macierzy

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1, 2] = 14 # wycinamy 7 i przypisujemy do tego miejsca 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Iteracja po tablicach

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat: # spłaszcza do postaci jedno wymiarowej
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


## Zmiana rozmiaru tabli

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel() # spłaszcza nasze dane do postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T # zamienia kolumny na wiersze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Maski logiczne

In [ ]:
A = np.arange(-10, 10, 0.5)
A = A.reshape(10,-1) # 10 daje nam ilość wiersz a -1 mowi żeby rozłozył na kolumny automatycznie
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0 # daje nam maske logiczną w macierzy tak gdzie wiekszę jest True

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A > 0] # da nam wartości tylko wieksze od 0

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
A[A < 0]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

In [ ]:
np.bitwise_and(A > -5, A < 5) # zwraca nam maskę gdzie ten warunek jest spełniony

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])

# ALGEBRA LINIOWA

## Norma wektora, długość wektora w R2

In [ ]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

## Norma euklidesowa Rm


In [ ]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

## Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

## Odległość dwóch punktów w przestrzeni Rm

In [ ]:
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

## Mnożenie macierzy

In [3]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)
# mnożąc macierze 2x2 z macieżą 2x1 otrzymamy macierz 2x1

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [5]:
z = np.dot(X, Y)
z

array([[ 2],
       [-6]])

In [7]:
z.shape

(2, 1)

In [8]:
X = np.array([[2,-1,3],
              [3,1,0]])
Y = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])
print(X, '\n')
print(Y)
# # mnożąc macierze 2x3 z macieżą 3x3 otrzymamy macierz 2x3
# tyle ile wierszy w pierwsze i tyle ile wierszy w drugiej macierzy

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [9]:
z = np.dot(X, Y)
z

array([[13,  9, -4],
       [ 6,  2, -1]])

## Wyznacznik macierzy

In [12]:
# wyznacznik macierzy oznaczamy |A|, liczmy poprzez odjecie iloczynu jednej przekątnej od drugiej
A = np.array([[2,4], [-1,3]])
np.linalg.det(A)
# zaokrąglamy
round(np.linalg.det(A))


10

## Ślad macierzy

In [13]:
# suma elemntów na przekątnej
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

## Macierz jednostkowa

In [14]:
# macierz kwadratowa która ma tyle samo wierszy i kolumn a przekątna jest równa 1
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
np.eye(3) # domyślnie ustawiony jest typ float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Macierz odwrotna

In [18]:
# AB=BA=daje macierz jednostkową
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [21]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

## Macierz transponowana

In [ ]:
# zamiana wierszy na kolumny, kolumny na wiersze

In [24]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [25]:
A.T

array([[ 2, -1],
       [ 4,  3]])

## Rozwiązywanie układów równań

In [27]:
A = np.array([[2,4], [1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [32]:
B = np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [33]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [34]:
X.shape

(2, 1)